Update webhook api && fix readme
antonmyronyuk/aioviberbot pull request #11
Opened 2024-06-12 18:24 UTC by lavrovas

- Fix readme typos
- Update webhook API for someone not willing to receive usernames and photos

2024-06-12 21:08 UTC, antonmyronyuk requested changes

2024-06-12 21:08 UTC, antonmyronyuk commented on aioviberbot/api/api.py
> +    async def set_webhook(self, url, webhook_events=None, send_name=True, send_photo=True, is_inline=False):
Hi, thank you for PR!

Let's change order of function params here: `send_name` and `send_photo` should be after exisiting `is_inline` param to keep backward compatibility (if someone uses non-keywords args for this method)

2024-06-12 21:08 UTC, antonmyronyuk commented on aioviberbot/api/api_request_sender.py
> +    async def set_webhook(self, url, webhook_events=None, send_name=True, send_photo=True, is_inline=False):
Params order should be changed here as well

2024-06-13 02:31 UTC, lavrovas commented on aioviberbot/api/api.py
> +    async def set_webhook(self, url, webhook_events=None, send_name=True, send_photo=True, is_inline=False):
By the way I cannot find anything about `is_inline` param in the API description, looks like it was removed a while ago.

2024-06-13 07:48 UTC, merged

2024-06-13 07:50 UTC, antonmyronyuk commented on aioviberbot/api/api.py
> +    async def set_webhook(self, url, webhook_events=None, send_name=True, send_photo=True, is_inline=False):
Got it, I'll remove it in next releases

2024-06-13 07:59 UTC, antonmyronyuk commented
Released in version `0.6.0` https://pypi.org/project/aioviberbot/0.6.0/